on:
  push:
    paths-ignore:
      - "docs/**"
      - "README.rst"
      - "CHANGELOG.md"
      - "CONTRIBUTING.rst"
      - ".github/workflows/docs.yml"
      - ".github/workflows/pages.yml"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "README.rst"
      - "CHANGELOG.md"
      - "CONTRIBUTING.rst"
      - ".github/workflows/docs.yml"
      - ".github/workflows/pages.yml"
name: build
jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        include:
          - clickhouse-version: 18.14.9
            clickhouse-org: yandex
          - clickhouse-version: 19.3.5
            clickhouse-org: yandex
          - clickhouse-version: 22.5.1.2079
            clickhouse-org: clickhouse
          - clickhouse-version: 23.8.4.69
            clickhouse-org: clickhouse
    services:
      clickhouse-server:
        image: ${{ matrix.clickhouse-org }}/clickhouse-server:${{ matrix.clickhouse-version }}
        ports:
          - 8123:8123
          - 9000:9000

    name: ${{ matrix.python-version }} CH=${{ matrix.clickhouse-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install test requirements
        run: |
          pip install --upgrade pip
          pip install pdm
          pdm install -G test -G lint -G coverage
      - name: Run prek
        run: pdm run prek-all
      - name: Run tests
        run: pdm run coverage --timeout=10 -v
        timeout-minutes: 2
      - name: Install coveralls
        run: |
          pdm install -G coverage
      - name: Upload coverage
        run: pdm run coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }} CH=${{ matrix.clickhouse-version }}

  coveralls-finished:
    name: Indicate completion to coveralls.io
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Finished
        uses: coverallsapp/github-action@v2.3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
