on: [push, pull_request]
name: build-docs
jobs:
  tests:
    runs-on: ubuntu-22.04
    name: Build docs
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          architecture: x64
      - name: Update tools
        run: |
          pip install --upgrade pip
          pip install pdm
      - name: Install docs requirements
        run: pdm install -G docs
      - name: Build docs
        run: pdm run docs
